### PR TITLE
Fix 'TypeError - hash key raise is not a Symbol' when used with Rails 6.0.3 - Try to pass the checks

### PR DESCRIPTION
**Pull request by wingice**

### CODE REVIEW

**Comment by wingice** [comment]
Another attempt to fix the issue and pass the checks.

**Comment by davekrupinski** [comment]
Any updates on this?

**Comment by wingice** [comment]
The checks failed because the proper bundler gem can't be found
```
Bundler could not find compatible versions for gem "bundler":
  In rails6.0:
    bundler (~> 1.7)
  Current Bundler version:
    bundler (2.2.0.dev)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?
```

**Comment by iGEL** [comment]
Sorry for the delay, it's now merged.

**Pull request merged**
