### PR TITLE
allow whitespace between key and value without it being considered part of value

### PR DESCRIPTION
**Pull request by rsl**

### CODE REVIEW

**Comment by rsl** [comment]
any chance of this being looked at?

**Comment by iGEL** [comment]
Sorry that I missed this. The change itself looks fine, but could you add or modify a spec to test this behavior?

**Comment by rsl** [comment]
updated

**Comment by rsl** [comment]
oh and i noticed you need to either nail down yr rack version or remove ruby 2.1 support on travis. rack 2.0.3 has not support under ruby 2.2.2. not sure which track you would rather take but heads up.

**Comment by iGEL** [comment]
Thank you! I squashed your commits in 36edb20 and pushed them to master.

**Pull request closed without merging**
